### ISSUE TITLE
关于夜间熄屏

### ISSUE THREAD

**Issue by windskyxb** [Temperature6/DevMonitor_for_Pis#1]
请问考虑加上夜间熄屏的功能吗？

**Comment by windskyxb** [comment]
目前是用sudo gpio write 10 0来把BLK引脚设为低电平来达到熄屏的目的

**Comment by Temperature6** [comment]
这种“即插即用”的程序，启动就直接运行，关闭就直接kill，可以写个服务管理BLK引脚和程序的运行应该就行了

**Comment by windskyxb** [comment]
> 这种“即插即用”的程序，启动就直接运行，关闭就直接kill，可以写个服务管理BLK引脚和程序的运行应该就行了

感谢！主要是devmonitor_lvgl_opi这个可执行文件强行停止后不会清屏，仍保留停止之前的界面；现在使用crontab来控制程序和BLK引脚
